### ISSUE TITLE
Examples of your current use cases and stability

### ISSUE THREAD

**Issue by whitwhoa** [yokai-php/batch-src#60]
Hello! I am currently looking into re-writing an ancient spring-batch application that my organization has supported for over a decade. The original developer is long gone, and I'm the only person on my team that has experience with Java. We are primarily a php shop, hints how I made my way here. 

I've been looking through the documentation and source code, however I was curious if you are currently using this in any production use cases, and what some of those use cases might be (not looking for any specifics, things such as queue emails, processing and parsing large data files, etc), as whatever this system gets re-written into must be stable, maintainable, and fail gracefully. 

My primary concern is that the application I'm looking to re-write handles some large text files many megs in some cases, and on occasion those files will contain invalid data and we must identify those crashes in order to correct them. Also, it used to be that long running php processes (some existing spring-batch jobs can take up to 2-3 hours) were unreliable and something to be avoided, but with all of the updates through out the years I'm curious if this is even still a concern? Have you experienced any issues with long running tasks which process large files?

Another question would be about concurrency. I see the SimpleJobLauncher executes jobs from the main process, but is there functionality to kick off multiple processes?

**Comment by yann-eugone** [comment]
​Hi there,

This library is running into multiple productions.
It became a standard into the company I work in.

We have many use cases :
- the most frequent is: read from a flat file, write to a database
- we also have the opposite quite often: read from database, write to a flat file
- but I also have made a "specific to standard converter" project, the idea was to remove all tenant specific code for software synchronisation, and wrap interaction around a standard importer (this project is connecting to flat files, web services, ... And produces collection of flat files to be imported in the SAAS software)

The `ItemJob` architecture is quite flexible, so you can do pretty much anything, this job will handle the batch processing for you:
- read from source
- try/catch every item tranform/write and report failures in `JobExecution`
- provide some Summary information about how much rows were successful, failed or warned

To be honest, I've never used spring batch myself. I went into the concept after working on a PHP product called [Akeneo](https://www.akeneo.com). The first commits are from this project (I wasn't able to use the Akeneo batch library because it is [not standalone](https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo/Tool/Bundle/BatchBundle)).
I've never experienced long time running jobs with this library, but :
- I've experienced it with PHP in general, and as long as you manage your memory, it should be fine
- I did had to work with very large CSV files (sometimes more than 1Gb) with this library, and as previously said, if you manage your memory, it works just fine

About concurrency, the `SimpleJobLauncher` is the simplest job launcher that exists.
But there is 2 other implementation :
- [`RunCommandJobLauncher`](https://github.com/yokai-php/batch-src/blob/0.x/src/batch-symfony-console/src/RunCommandJobLauncher.php) that is calling a CLI command in the background, and this command will execute the job
- [`DispatchMessageJobLauncher`](https://github.com/yokai-php/batch-src/blob/0.x/src/batch-symfony-messenger/src/DispatchMessageJobLauncher.php) that is dispatching a messenge in Symfony's messenger bus, which can be configured as asynchronous (as explained in the doc)

**Comment by whitwhoa** [comment]
Excellent! Thank you for the prompt response. We will definitely be taking a deeper dive into this. As far as administration goes (and this might be something I've missed when looking through the source) do you have a gui admin panel for monitoring active/pending/failed/etc job statuses? Or how are you monitoring the jobs?

**Comment by yann-eugone** [comment]
I've developed an admin panel around this library, but it has never been open sourced, maybe i can push the code in a sample project so you can grab it for your own use ?
(It is hard to Open Source frontend devs because : styles are always different, assets building is never done the same way, ...)

Examples in a SonataAdmin interface (sorry it's all french translated)

![image](https://user-images.githubusercontent.com/1303838/167095739-e69003fe-68fb-435b-9d4e-0b2aa743f1e0.png)
![image](https://user-images.githubusercontent.com/1303838/167095837-f6c452a2-ecc0-4bb5-ae11-fded03d78688.png)

**Comment by whitwhoa** [comment]
If you are open to creating an example project for the admin panel I would for sure check it out! :)

**Comment by yann-eugone** [comment]
Pushed it right now : https://github.com/yann-eugone/yokai-batch-ui

**Comment by yann-eugone** [comment]
I'm closing the issue, as I think it has been answered. But feel free to reopen if something else comes to your mind.
